# Generated by Django 5.0.2 on 2024-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_brand_alter_instrument_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instruments/'),
        ),
    ]
