# Generated by Django 5.0.2 on 2024-03-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrument_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='product',
            field=models.CharField(default='produto não especificado', max_length=50),
        ),
    ]
