# Generated by Django 5.0.2 on 2024-03-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_instrument_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('Guitarras', 'Guitarras'), ('Violões', 'Violões'), ('Baixos', 'Baixos'), ('Baterias e pratos', 'Baterias e pratos'), ('Cavaquinhos', 'Cavaquinhos'), ('Teclados e pianos', 'Teclados e pianos'), ('Violinos e violoncellos', 'Violinos e violoncellos'), ('Instrumentos de sopro', 'Instrumentos de sopro'), ('Amplificadores e microfones', 'Amplificadores e microfones'), ('Outros instrumentos', 'Outros instrumentos'), ('Acessórios', 'Acessórios')], default='Outros instrumentos', max_length=50),
        ),
    ]
