# Generated by Django 5.0.2 on 2024-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_alter_instrument_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
